baseURL = "https://marinhero.com"
languageCode = "en-us"
title = "Marín Alcaraz"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Marín Alcaraz"

[[menu.main]]
    name = "About"
    url  = "https://github.com/marinhero/hugo-black-and-light-theme"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/marinhero"
[[menu.main]]
    name = "Strava"
    url  = "https://www.strava.com/athletes/9416766"

